version: 2.1

orbs:
  cypress: cypress-io/cypress@1.26.0
  pytest: thekevjames/pytest@0.0.60

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.9.0
        environment:
          MONGO_USER_HOST: host

    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install -r requirements.txt
      - run:
          name: Change test.py script file permissions
          command: sudo chmod +rx ./test_codes/test.py

      - run:
          command: test_codes/test.py
          name: Test

workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
      - build-and-test

