version: 2.1

orbs:
  cypress: cypress-io/cypress@1.26.0

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.9.0
        environment:
          MONGO_USER_HOST: api.simon-park.codes
          MONGO_USER_PORT: 27017
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Change test.py script file permissions
          command: sudo chmod +rx ./test_codes/test.py
      - run:
          name: run test
          command: |
            . venv/bin/activate
            python3 -m pytest test_codes/test.py
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
      - build-and-test

