version: 2.1

orbs:
  cypress: cypress-io/cypress@1.26.0
  pytest: thekevjames/pytest@0.0.60
  python: circleci/python@1.0.0

workflows:
  jobs:
    build-and-test:
      docker:
      - image: cimg/python:3.9.0
    steps:
      - checkout
      - run:
          name: run test
          commands: python -m pytest test_codes/test.py
# workflows:
#   build:
#     jobs:
#       - cypress/run:
#           yarn: true
#       - build-and-test

