version: 2.1

orbs:
  cypress: cypress-io/cypress@1.26.0
  pytest: thekevjames/pytest@0.0.60

jobs:
  build-and-test:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
        command: chmod +x ./test_codes/test.py
        # command: ./test_codes/test.py test
        name: Test

workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
      - build-and-test

