version: 2.1

orbs:
  cypress: cypress-io/cypress@1.26.0
  pytest: thekevjames/pytest@0.0.60
  python: circleci/python@1.0.0

jobs:
  publish:
    executor: python/default
    steps:
      - checkout
      - python/dist
      - run: python -m pytest test_codes/test.py

workflows:
  main:
    jobs:
      - python/test:
          test-tool: pytest
      - publish
# workflows:
#   build:
#     jobs:
#       - cypress/run:
#           yarn: true
#       - build-and-test

