version: 2.1

orbs:
  cypress: cypress-io/cypress@1.26.0
  pytest: thekevjames/pytest@0.0.60

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.9.0
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install -r requirements.txt
      - run:
          name: Change test.py script file permissions
          command: sudo chmod +rx ./test_codes/test.py
      - run:
          name: run tests
          command: |
            python3.9.0 -m venv venv
            source venv/bin/activate
            mkdir test-results
            pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
      - build-and-test

